// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVLM-BA4cXtjytf5mCHA66vDUZp9kQ1cc',
    appId: '1:742898064871:web:fda2701169692261247142',
    messagingSenderId: '742898064871',
    projectId: 'conet-3524c',
    authDomain: 'conet-3524c.firebaseapp.com',
    storageBucket: 'conet-3524c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUk0Po6BJaRJOQwxBL0xZOPT9pVBkgk1I',
    appId: '1:742898064871:android:825a2ac96d22dc9f247142',
    messagingSenderId: '742898064871',
    projectId: 'conet-3524c',
    storageBucket: 'conet-3524c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_ZSpVaqvTk2h9dLbLNEQymAlE6EEpURY',
    appId: '1:742898064871:ios:19e1e2cc6eac64ac247142',
    messagingSenderId: '742898064871',
    projectId: 'conet-3524c',
    storageBucket: 'conet-3524c.firebasestorage.app',
    iosBundleId: 'com.example.conetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_ZSpVaqvTk2h9dLbLNEQymAlE6EEpURY',
    appId: '1:742898064871:ios:19e1e2cc6eac64ac247142',
    messagingSenderId: '742898064871',
    projectId: 'conet-3524c',
    storageBucket: 'conet-3524c.firebasestorage.app',
    iosBundleId: 'com.example.conetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVLM-BA4cXtjytf5mCHA66vDUZp9kQ1cc',
    appId: '1:742898064871:web:351de3469a3e644f247142',
    messagingSenderId: '742898064871',
    projectId: 'conet-3524c',
    authDomain: 'conet-3524c.firebaseapp.com',
    storageBucket: 'conet-3524c.firebasestorage.app',
  );
}
